---
- hosts: all
  sudo: yes
  vars_files:
    - vars/user.yml
    - vars/nginx.yml
    - vars/php.yml
  roles:
    #- { role: abaez.docker }
    - { role: ANXS.generic-users }
    - { role: geerlingguy.nginx }
    #- { role: geerlingguy.php } <- Currently buggy, Preinstalling via shellscript
