VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "file://centos72-0.1.0.box"
    config.vm.host_name = "dev.local"
    config.vm.network "public_network", ip: "192.168.1.30"
    config.vm.network "forwarded_port", guest: 80, host: 80

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "dev.local"]
        vb.customize ["modifyvm", :id, "--memory", 1024]
    end

    config.vm.provision "shell", path: "provision/shell/setup.sh"

    config.vm.provision "ansible_local" do |ansible|
        ansible.verbose  = true
        ansible.galaxy_role_file = "provision/ansible/requirements.yml"
        ansible.playbook = "provision/ansible/playbook.yml"
    end

    config.vm.provision "shell", path: "provision/shell/finish.sh"

    config.vm.synced_folder "../project", "/var/www/vhosts/dev.local", create: true
end
